blank_issues_enabled: false
contact_links:
  - name: Support Discord Lyxios
    url: https://discord.gg/RZHrtzwUC2
    about: Pour toute question ou demande de support direct sur le bot Discord Lyxios.

